package interfaces;


import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import dao.UsuarioDAO;
import modelo.Usuario;

import javax.swing.GroupLayout.Alignment;

import java.awt.event.ActionEvent;

import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JFrame;



/**
 *
 * @author Home
 */
public class jifcadastro extends javax.swing.JFrame {

    /**
     * Creates new form jifcadastro
     */
    public jifcadastro() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jtnome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jtend = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jttelefone = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jbinserir = new javax.swing.JButton();
        jbcancelar = new javax.swing.JButton();
        jbcancelar.setText("Cancelar");
        jScrollPane1 = new javax.swing.JScrollPane();
        jtb1 = new javax.swing.JTable();
        jtentrada = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtsaida = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtdata = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setTitle("Gerenciamento Laboratorios William Alcantara Coelho da Cruz");

        jLabel1.setText("Nome");

        jLabel2.setText("Numero do Lab Escolhido");

        jLabel3.setText("Telefone");

        jbinserir.setText("Inserir");
        jbinserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbinserirActionPerformed(evt);
            }
        });

        jbcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbapagarActionPerformed(evt);
                
          }
        });

        jtb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Laboratorio", "Telefone", "Entrada", "Saida", "Data"
            }
        ));
        jScrollPane1.setViewportView(jtb1);

        jLabel4.setText("Hora de Entrada");

        jLabel5.setText("Hora de Saida");

        jLabel6.setText("Data");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(24)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jScrollPane1, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
        				.addGroup(layout.createSequentialGroup()
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
        							.addComponent(jtnome, GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
        							.addComponent(jLabel1)
        							.addComponent(jtentrada))
        						.addGroup(layout.createSequentialGroup()
        							.addComponent(jbinserir)
        							.addGap(18)
        							.addComponent(jbcancelar))
        						.addComponent(jLabel4))
        					.addGap(31)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(layout.createParallelGroup(Alignment.LEADING)
        							.addComponent(jtend, GroupLayout.PREFERRED_SIZE, 157, GroupLayout.PREFERRED_SIZE)
        							.addComponent(jtsaida, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 157, GroupLayout.PREFERRED_SIZE))
        						.addComponent(jLabel5)
        						.addComponent(jLabel2))
        					.addPreferredGap(ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(jLabel3)
        						.addComponent(jLabel6)
        						.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
        							.addComponent(jttelefone, GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
        							.addComponent(jtdata)))))
        			.addGap(42))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(16)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel1)
        				.addComponent(jLabel3)
        				.addComponent(jLabel2))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jtnome, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jtend, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jttelefone, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(25)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel4)
        				.addComponent(jLabel6)
        				.addComponent(jLabel5))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jtentrada, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jtsaida, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jtdata, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(63)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jbinserir)
        				.addComponent(jbcancelar))
        			.addGap(27)
        			.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 94, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(78, Short.MAX_VALUE))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>                        

    private void jbinserirActionPerformed(java.awt.event.ActionEvent evt) {                                          
       Usuario user = new Usuario();
       user.setId(0);
       user.setJtnome(jtnome.getText());
       user.setJtend(jtend.getText());
       user.setJttelefone(jttelefone.getText());
       user.setJtentrada(jtentrada.getText());
       user.setJtsaida(jtsaida.getText());
       user.setJtdata(jtdata.getText());
       
       
        String nome = jtnome.getText().trim();
        String end = jtend.getText().trim();
        String tel = jttelefone.getText();
        String entrada = jtentrada.getText();
        String saida = jtsaida.getText();
        String data = jtdata.getText();
   
        // fazendo a validação dos dados
		if ((jtnome.getText().isEmpty()) || (jtentrada.getText().isEmpty()) || (jtend.getText().isEmpty()) || (jtsaida.getText().isEmpty()) || (jttelefone.getText().isEmpty()) || (jtdata.getText().isEmpty())) {
		   JOptionPane.showMessageDialog(null, "Todos os campos devem ser preenchidos!!!");
		}
		else {
		
					        
        DefaultTableModel val = (DefaultTableModel)jtb1.getModel();
        val.addRow(new String[]{nome,end,tel,entrada,saida,data});
        jtnome.setText("");
        jtend.setText("");
        jttelefone.setText("");
        jtentrada.setText("");
        jtsaida.setText("");
        jtdata.setText("");
        
        jtnome.requestFocus();
			
        // instanciando a classe UsuarioDAO do pacote dao e criando seu objeto dao
		UsuarioDAO userdao = new UsuarioDAO();
		userdao.inserir(user);
		
	    
        JOptionPane.showMessageDialog(null, "Cadastro realizado com sucesso!!!");
    }  	}                                       

    private void jbapagarActionPerformed(java.awt.event.ActionEvent evt) {                                         
        
        //((DefaultTableModel) jtb1.getModel()).removeRow(jtb1.getSelectedRow());
    
			System.exit(0); 
		
    
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jifcadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jifcadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jifcadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jifcadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jifcadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbcancelar;
    private javax.swing.JButton jbinserir;
    private javax.swing.JTable jtb1;
    private javax.swing.JTextField jtdata;
    private javax.swing.JTextField jtend;
    private javax.swing.JTextField jtentrada;
    private javax.swing.JTextField jtnome;
    private javax.swing.JTextField jtsaida;
    private javax.swing.JTextField jttelefone;
                      
	
    
   
}